name: double_tap_player_view_plus
description: a widget to handle fast forward/rewind behavior by double tap and horizontal drag like a video player.
version: 2.0.3
homepage: https://github.com/tachibana-shin/double_tap_player_view_plus
repository: https://github.com/tachibana-shin/double_tap_player_view_plus

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  freezed_annotation: ^2.2.0
  circular_reveal_animation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner:
  flutter_lints: ^2.0.1
